import { Router } from 'express';
import { createPayment, webhook } from './payments.controller';
import { validate } from '../../middleware/validate';
import { authenticate } from '../../middleware/authenticate';
import { createPaymentSchema, webhookSchema } from './payments.schema';
import { asyncHandler } from '../../utils/asyncHandler';

const router = Router();

/**
 * @openapi
 * /api/payments:
 *   post:
 *     tags: [Payments]
 *     summary: Process payment for a booking
 *     description: Idempotent — repeat requests with the same `Idempotency-Key` return the original result.
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: header
 *         name: Idempotency-Key
 *         required: false
 *         schema: { type: string }
 *         description: Unique key; generated by the server if omitted
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/PaymentCreate'
 *     responses:
 *       '200':
 *         description: Payment processed (simulated success/failure)
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 data:
 *                   $ref: '#/components/schemas/PaymentResult'
 *       '400':
 *         $ref: '#/components/responses/BadRequest'
 *       '401':
 *         $ref: '#/components/responses/Unauthorized'
 *       '403':
 *         $ref: '#/components/responses/Forbidden'
 *       '404':
 *         $ref: '#/components/responses/NotFound'
 */
router.post(
  '/',
  authenticate,
  validate({ body: createPaymentSchema }),
  asyncHandler(createPayment),
);

/**
 * @openapi
 * /api/payments/webhook:
 *   post:
 *     tags: [Payments]
 *     summary: Receive payment status updates
 *     description: Requires an HMAC-SHA256 signature of the raw body in `X-Webhook-Signature`. Duplicate event IDs are ignored.
 *     parameters:
 *       - in: header
 *         name: X-Webhook-Signature
 *         required: true
 *         schema: { type: string }
 *         description: Hex-encoded HMAC-SHA256 of the raw request body using `WEBHOOK_SECRET`
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/WebhookPayload'
 *     responses:
 *       '200':
 *         description: 'Event processed (duplicate=true if already seen)'
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 data:
 *                   $ref: '#/components/schemas/WebhookResult'
 *       '400':
 *         $ref: '#/components/responses/BadRequest'
 *       '401':
 *         $ref: '#/components/responses/Unauthorized'
 */
router.post(
  '/webhook',
  validate({ body: webhookSchema }),
  asyncHandler(webhook),
);

export { router as paymentsRoutes };